"""empty message

Revision ID: 4540fc99c2e0
Revises: 16dccef54c63
Create Date: 2015-08-25 18:19:57.093598

"""

# revision identifiers, used by Alembic.
revision = '4540fc99c2e0'
down_revision = '16dccef54c63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('tag', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'tag')
    ### end Alembic commands ###
