"""empty message

Revision ID: 2d6fe23635d1
Revises: 531f091961cd
Create Date: 2015-08-25 15:06:16.715972

"""

# revision identifiers, used by Alembic.
revision = '2d6fe23635d1'
down_revision = '531f091961cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit', sa.Column('tag', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit', 'tag')
    ### end Alembic commands ###
